# permissions for end users to view services.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: service-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pac
    app.kubernetes.io/part-of: pac
    app.kubernetes.io/managed-by: kustomize
  name: service-viewer-role
rules:
- apiGroups:
  - app.pac.io
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.pac.io
  resources:
  - services/status
  verbs:
  - get
