---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.pac.io
  resources:
  - catalogs
  - configs
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.pac.io
  resources:
  - catalogs/finalizers
  - configs/finalizers
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - app.pac.io
  resources:
  - catalogs/status
  - configs/status
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - manageiq.pac.io
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manageiq.pac.io
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - manageiq.pac.io
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
