apiVersion: app.pac.io/v1alpha1
kind: Catalog
metadata:
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: medium-vm
    app.kubernetes.io/part-of: pac
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pac
  name: medium-vm
spec:
  type: VM
  capacity:
    cpu: '0.5'
    memory: 8
  description: 'Medium size vm'
  expiry: 20
  image_thumbnail_reference: 'https://sample-image/centos-symbol-x256.png'
  vm:
    crn: 'crn:v1:bluemix:public:power-iaas:lon06:a/<accountID>:<powerVSInstanceID>::'
    image: <sampleImageName>
    network: <sampleNetworkName>
    processor_type: shared
    system_type: s922
    capacity:
      cpu: '0.5'
      memory: 8
