apiVersion: app.pac.io/v1alpha1
kind: Config
metadata:
  labels:
    app.kubernetes.io/name: config
    app.kubernetes.io/instance: config-sample
    app.kubernetes.io/part-of: pac
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pac
  name: config-sample
spec:
  # TODO(user): Add fields here
