apiVersion: manageiq.pac.io/v1alpha1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: service-sample
    app.kubernetes.io/part-of: pac
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pac
  name: service-sample
spec:
  type: vm
  virtualMachine:
    name: mkumatag-pac-ws
    ports:
      - 22
      - 443
    cloudInstanceID: f652853b-c022-405e-9f11-e30259f930e7
    zone: lon06
    vpc:
      ID: r018-339f44d6-5878-4c79-915c-0f7b8f910a33
      region: eu-gb
      loadbalancer: r018-5bc93b5c-5dc2-4197-a37a-5ebe00b11070
