apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: pac
    app.kubernetes.io/part-of: pac
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: pac
    app.kubernetes.io/part-of: pac
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - "--manager-type=config"
        - "--leader-elect"
        - "--health-probe-bind-address=:8081"
        - "--metrics-bind-address=127.0.0.1:8080"
        - "--leader-elect"
        - "--zap-time-encoding=iso8601"
        - "--sync-period=2m"
        image: controller:latest
        imagePullPolicy: Always
        name: manager-config
#        env:
#        - name: IBMCLOUD_APIKEY
#          valueFrom:
#            secretKeyRef:
#              name: ibm-credential
#              key: IBMCLOUD_APIKEY
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      - command:
          - /manager
        args:
          - "--manager-type=service"
          - "--leader-elect"
          - "--health-probe-bind-address=:8082"
          - "--metrics-bind-address=127.0.0.1:8083"
          - "--leader-elect"
          - "--zap-time-encoding=iso8601"
          - "--sync-period=10m"
        image: controller:latest
        imagePullPolicy: Always
        name: manager-service
        env:
          - name: IBMCLOUD_APIKEY
            valueFrom:
              secretKeyRef:
                name: ibm-credential
                key: IBMCLOUD_APIKEY
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      imagePullSecrets:
      - name: regcred
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
