name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Calling reusable workflow
  call-fetch-go-version:
    uses: ./.github/workflows/fetch-go-version.yml

  e2e-tests:
    runs-on: ubuntu-latest
    needs: call-fetch-go-version
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.call-fetch-go-version.outputs.go-version }}
          cache: false

      - name: Set up Podman
        run: |
          sudo apt install -y podman-docker
          sudo apt install -y podman-compose

      - name: Run e2e tests
        run: |
          make test-e2e
