name: Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Calling reusable workflow
  call-fetch-go-version:
    uses: ./.github/workflows/fetch-go-version.yml

  unit_test:
    runs-on: ubuntu-latest
    needs: call-fetch-go-version
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.call-fetch-go-version.outputs.go-version }}
          cache: false

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests
        run: |
          mkdir -p out
          go test -coverprofile=out/coverage.out -v ./...

      - name: Generate HTML coverage report
        run: |
          go tool cover -html=out/coverage.out -o out/coverage.html

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            out/coverage.out
            out/coverage.html
